version: "3"

services:
  demos:
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./tests:/workspace/tests
      - ./imantics:/workspace/libs/imantics
    build: .
